version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile   # ← use the new root-level Dockerfile
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - .:/app                          # ← mount full repo, not just frontend
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
  
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT:-3000}
    volumes:
      - ./apps/backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis

volumes:
  frontend_node_modules:
  backend_node_modules:
  redis_data:
